{{- if .Values.createNamespace}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
{{- end}}
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-helloWorld-svc
#   labels:
#     app: helloworld
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#   selector:
#     app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: {{.Values.namespace}}
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: IfNotPresent
        name: helloworld-state-hc2cp
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1024Mi
            cpu: 100m
          requests:
            memory: 1024Mi
            cpu: 100m
